### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by jbeguna04**
This Is the file I have added on your assets containing the new designs of the application. Thank You!

### CODE REVIEW

**Comment by kapito** [comment]
Sorry, I'm very busy at the moment so will need to find a couple hours this week to add these (+ some other minor changes I want to make to the app). These will definitely be added however, thank you!

**Comment by jbeguna04** [comment]
You can also use it on your readme

**Comment by kapito** [comment]
Hi, I plan to add this on Saturday as I'm currently away from my PC for a few days, sorry for the wait!

**Comment by kapito** [comment]
Closing in favour of #8 (which adds credits to you as well). Many thanks!

**Pull request closed without merging**
